package:
  name: deepgraph
  version: "0.0.1"

build:
  number: 1
  script:
    - echo "This is my anaconda build with conda"

source:
  git_rev: v0.0.1
  git_url: https://github.com/deepgraph/deepgraph.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
  run:
    - python
    - numpy 
    - pandas

source:
  path: /home/macaco/Work/git/deepgraph/conda_build/

about:
  summary: DeepGraph is an efficient, general-purpose data analysis Python package. Based on pandas DataFrames, it provides the means to analyze data via graph theory (a.k.a. networks).
  home: https://github.com/deepgraph/deepgraph
  license: BSD

