package:
  name: deepgraph
  version: "0.0.5"

build:
  number: 0

source:
  # fn: DeepGraph-0.0.5.tar.gz
  # url: https://pypi.python.org/packages/source/D/DeepGraph/DeepGraph-0.0.5.tar.gz
  # md5: 63ff3877e8c6342413b9d617856100db
  git_url: https://github.com/deepgraph/deepgraph.git
  git_rev: master  # 0.0.5

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
  files:
    - ../tests/test_DeepGraph.py
    - ../tests/test_CreateEdges.py
  requires:
    - deepgraph
    - pytest
    - numpy
    - pandas
    # - tables
    - scipy
    - networkx
  imports:
    - deepgraph
  commands:
    # - pip install tables
    - conda install -y -n _test -c https://conda.anaconda.org/anaconda pytables
    - py.test -v

about:
  summary: >
    DeepGraph is a scalable, general-purpose data analysis package. It
    implements a network representation based on pandas DataFrames and
    provides methods to construct, partition and plot graphs, to interface
    with popular network packages and more.
  home: https://github.com/deepgraph/deepgraph
  license: BSD

