package:
  name: deepgraph
  version: "0.0.1"

build:
  number: 1
  script:
    - echo "This is my anaconda build with conda"

source:
  fn: DeepGraph-0.0.1.tar.gz
  url: https://pypi.python.org/packages/source/D/DeepGraph/DeepGraph-0.0.1.tar.gz
  md5: b581a944b8de37095210668383bc2652

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
    requires:
      - pytest
      - numpy
      - pandas
    imports:
      - deepgraph
      - numpy 
      - pandas
    commands:
      - py.test -v

about:
  summary: DeepGraph is an efficient, general-purpose data analysis Python package. Based on pandas DataFrames, it provides the means to analyze data via graph theory (a.k.a. networks).
  home: https://github.com/deepgraph/deepgraph
  license: BSD

