package:
  name: deepgraph
  version: "0.0.1"

build:
  number: 0

source:
  fn: DeepGraph-0.0.2.tar.gz
  url: https://pypi.python.org/packages/source/D/DeepGraph/DeepGraph-0.0.2.tar.gz
  md5: a8be4e5f3523ff6f59c037bd319d72f0
  # git_url: https://github.com/deepgraph/deepgraph.git
  # git_rev: master  # 0.0.1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
  files:
    - ../tests/test_DeepGraph.py
    - ../tests/test_CreateEdges.py
  requires:
    - deepgraph
    - pytest
    - numpy
    - pandas
    # - tables
    - scipy
    - networkx
  imports:
    - deepgraph
  commands:
    # - pip install tables
    - conda install -y -n _test -c https://conda.anaconda.org/anaconda pytables
    - py.test -v

about:
  summary: DeepGraph is an efficient, general-purpose data analysis Python package. Based on pandas DataFrames, it provides the means to analyze data via graph theory (a.k.a. networks).
  home: https://github.com/deepgraph/deepgraph
  license: BSD

